services:
  db:
    container_name: 'market-database'
    image: 'mysql:latest'
    environment:
      - "MYSQL_DATABASE=${MYSQL_DATABASE_NAME}"
      - "MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}"
    ports:
      - '3306:3306'
    healthcheck:
        test: [ 'CMD', 'mysqladmin', 'ping', '-h', 'localhost' ]
        interval: 6s
        timeout: 5s
        retries: 3
    networks:
        - trade-market
  app:
    container_name: "market-app"
    build: .
    environment:
      - "SPRING_DATASOURCE_PASSWORD=${MYSQL_ROOT_PASSWORD}"
      - "SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/${MYSQL_DATABASE_NAME}"
      - "SPRING_JPA_HIBERNATE_DDL_AUTO=update"
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    networks:
      - trade-market
networks:
  trade-market:
